BAHN_BOT_NAME = "testbot"
BAHN_BOT_PW = "D2PcQ9yCs&MXB8k"
BAHN_NAME = "RE7"
# zkNQE4hQkAaxufN6H
ANNOUNCE_CHANNEL = "zkNQE4hQkAaxufN6H"
FLAIRS = {-1: "📛", 0: "ℹ️", 1: "✅"}

STATION_ID = "6620"
PRODUCT_ID = "7"
TRAIN_NUMBER = "32529"
TRAIN_NAME = "RE7"
